overblog_graphql:
    services:
        promise_adapter: "graphql_promise_adapter"
    definitions:
        schema:
            query: Query
            types:
                - GeometryPoint
                - GeometryMultiPoint
                - GeometryLineString
                - GeometryMultiLineString
                - GeometryPolygon
                - GeometryMultiPolygon
        mappings:
            types:
                -
                    type: yaml
                    dir: "%kernel.project_dir%/config/graphql/types"
                    suffix: null
