-- Revert geoname:0001_extensions from pg

BEGIN;

  DROP EXTENSION IF EXISTS "ltree" CASCADE;
  DROP EXTENSION IF EXISTS "postgis" CASCADE;
  DROP EXTENSION IF EXISTS "unaccent" CASCADE;
  DROP EXTENSION IF EXISTS "citext" CASCADE;
  DROP EXTENSION IF EXISTS "uuid-ossp" CASCADE;

COMMIT;
