<?php
/**
 * This file has been automatically generated by Pomm's generator.
 * You MIGHT NOT edit this file as your changes will be lost at next
 * generation.
 */

namespace App\Database\Model\Geoname\ExecutiveSchema\AutoStructure;

use PommProject\ModelManager\Model\RowStructure;

/**
 * Localization
 *
 * Structure class for relation executive.localization.
 * 
 * Class and fields comments are inspected from table and fields comments.
 * Just add comments in your database and they will appear here.
 * @see http://www.postgresql.org/docs/9.0/static/sql-comment.html
 *
 *
 *
 * @see RowStructure
 */
class Localization extends RowStructure
{
    /**
     * __construct
     *
     * Structure definition.
     *
     * @access public
     */
    public function __construct()
    {
        $this
            ->setRelation('executive.localization')
            ->setPrimaryKey(['id'])
            ->addField('id', 'int8')
            ->addField('gid', 'public.global_id')
            ->addField('uuid', 'uuid')
            ->addField('created_at', 'timestamptz')
            ->addField('updated_at', 'timestamptz')
            ->addField('deleted_at', 'timestamptz')
            ->addField('data', 'jsonb')
            ->addField('alt', 'jsonb')
            ->addField('active', 'bool')
            ->addField('name', 'text')
            ->addField('type', 'public.tag3d')
            ->addField('tags', 'public.tag3d_array')
            ->addField('coordinates', 'public.geometry')
            ->addField('path', 'public.ltree')
            ->addField('id_parent', 'int8')
            ;
    }
}
